apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: actual-guanaco-dotnet-basic 
  janus-idp.io/tekton: actual-guanaco-dotnet-basic
  backstage.io/kubernetes-id: actual-guanaco-dotnet-basic
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: actual-guanaco-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  